# Generated by Django 4.2.3 on 2023-07-18 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='uid',
        ),
    ]
