# Generated by Django 4.2.3 on 2023-07-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_remove_person_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uniqID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
