# Generated by Django 4.2.3 on 2023-07-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_person_uniqid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='uniqID',
        ),
        migrations.AddField(
            model_name='person',
            name='validated',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
