# Generated by Django 4.2.3 on 2023-07-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_alter_person_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
