# Generated by Django 4.2.3 on 2023-07-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_alter_person_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='validated',
        ),
        migrations.AddField(
            model_name='person',
            name='validation',
            field=models.BooleanField(default=False),
        ),
    ]
