# Generated by Django 4.2.3 on 2023-07-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0007_remove_person_validated_person_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='validation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
