# Generated by Django 4.2.3 on 2023-07-19 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_alter_person_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='validation',
        ),
    ]
