# Generated by Django 4.2.3 on 2023-07-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_remove_person_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='code_validation',
            field=models.BooleanField(null=True),
        ),
    ]
