# Generated by Django 4.2.3 on 2023-07-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_rename_code_validation_person_valid_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='person_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
