# Generated by Django 4.2.3 on 2023-07-27 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_validation_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_times', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='validation',
            name='person_id',
        ),
        migrations.AddField(
            model_name='validation',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='lname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
