# Generated by Django 4.2.3 on 2023-07-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_invitation_invitees_alter_invitation_meeting_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invitees',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='meeting_times',
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.person'),
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_dt', models.TextField()),
                ('invitation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.invitation')),
                ('invitee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.person')),
            ],
        ),
    ]
