# Generated by Django 4.2.3 on 2023-08-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_remove_invitation_invitees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='is_available',
            field=models.BooleanField(null=True),
        ),
    ]
